name: engine_tests

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  test: 1.16.8
  path: 1.8.0
  image: 3.0.2
  vm_service: 6.2.0

dependency_overrides:
 sky_engine:
   path: ../../../out/host_debug_unopt/gen/dart-pkg/sky_engine
 sky_services:
   path: ../../../out/host_debug_unopt/gen/dart-pkg/sky_services
